/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Robot */

#ifndef _Included_Robot
#define _Included_Robot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Robot
 * Method:    getPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Robot_getPosition
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
