/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Robot */

#ifndef _Included_Robot
#define _Included_Robot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Robot
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Robot_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
