/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Robot */

#ifndef _Included_Robot
#define _Included_Robot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Robot
 * Method:    mWiiUpdate
 * Signature: ([S[S)V
 */
JNIEXPORT void JNICALL Java_Robot_mWiiUpdate
  (JNIEnv *, jobject, jshortArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
